### ISSUE TITLE
RSS River plugin hangs /_cat and /_cluster APIs on ElasticSearch 1.4.3

### ISSUE THREAD

**Issue by ignaciovazquez** [dadoonet/rssriver#43]
It looks like the /_cat and /_cluster APIs don't work anymore after upgrading ElasticSearch to 1.4.3.

As I mentioned in #42 I can't run the tests with maven with the current pom.xml, but if I build the plugin and install it, everything in ES works but those endpoints.

I've created a ticket at the elasticsearch repo, but it looks like it's related to this plugin.

https://github.com/elasticsearch/elasticsearch/issues/9713

Thanks for maintaining such a useful project!

Ignacio

**Comment by dadoonet** [comment]
Project stopped.
