### ISSUE TITLE
ES 1.5.2 rssriver

### ISSUE THREAD

**Issue by pinkdevelops** [dadoonet/rssriver#44]
Has anyone been able to get RssRiver working on ES 1.5.2?  I have been working through the pom.xml with no luck.  output on mvn clean install on master branch:

mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Elasticsearch RSS River Plugin 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ rssriver ---
[INFO] Deleting /opt/elasticsearch-1.5.2/riverSource/rssriver-master/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ rssriver ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rssriver ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ rssriver ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /opt/elasticsearch-1.5.2/riverSource/rssriver-master/target/classes
[WARNING] /opt/elasticsearch-1.5.2/riverSource/rssriver-master/src/main/java/org/elasticsearch/river/rss/RssRiver.java: Some input files use or override a deprecated API.
[WARNING] /opt/elasticsearch-1.5.2/riverSource/rssriver-master/src/main/java/org/elasticsearch/river/rss/RssRiver.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rssriver ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 10 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ rssriver ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /opt/elasticsearch-1.5.2/riverSource/rssriver-master/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.13:test (default-test) @ rssriver ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- junit4-maven-plugin:2.0.12:junit4 (tests) @ rssriver ---
[INFO] <JUnit4> says g'day! Master seed: 1D4A2CDBC54E0CFF
Executing 3 suites with 1 JVM.

Started J0 PID(13780@ip-10-0-1-120).
Suite: org.elasticsearch.river.rss.integration.RssRiverAllParametersTest
ERROR   0.00s | RssRiverAllParametersTest (suite) <<<
   > Throwable #1: java.lang.NoSuchMethodError: org.apache.lucene.util.StringHelper.randomId()[B
   > 	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:143)
   > 	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:52)
   > 	at org.elasticsearch.test.ElasticsearchTestCase.<clinit>(ElasticsearchTestCase.java:97)
   > 	at java.lang.Class.forName0(Native Method)
   > 	at java.lang.Class.forName(Class.java:348)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$1.run(RandomizedRunner.java:553)
Completed in 1.26s, 0 tests, 1 error <<< FAILURES!

Suite: org.elasticsearch.river.rss.unit.RomeTest
ERROR   0.03s | RomeTest.initializationError <<<
   > Throwable #1: java.lang.NoClassDefFoundError: org.elasticsearch.test.ElasticsearchTestCase
   > 	at java.lang.Class.getDeclaredMethods0(Native Method)
   > 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
   > 	at java.lang.Class.getDeclaredMethods(Class.java:1975)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$3.members(ClassModel.java:215)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$3.members(ClassModel.java:212)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$ModelBuilder.build(ClassModel.java:85)
   > 	at com.carrotsearch.randomizedtesting.ClassModel.methodsModel(ClassModel.java:212)
   > 	at com.carrotsearch.randomizedtesting.ClassModel.<init>(ClassModel.java:207)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner.<init>(RandomizedRunner.java:319)
   > 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   > 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   > 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   > 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
   > 	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)
   > 	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)
   > 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
   > 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
   > 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
   > 	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
   > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:194)
   > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:310)
   > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
Completed in 0.09s, 1 test, 1 error <<< FAILURES!

Suite: org.elasticsearch.river.rss.unit.RssToJsonTest
ERROR   0.05s | RssToJsonTest.initializationError <<<
   > Throwable #1: java.lang.NoClassDefFoundError: org.elasticsearch.test.ElasticsearchTestCase
   > 	at java.lang.Class.getDeclaredMethods0(Native Method)
   > 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
   > 	at java.lang.Class.getDeclaredMethods(Class.java:1975)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$3.members(ClassModel.java:215)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$3.members(ClassModel.java:212)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$ModelBuilder.build(ClassModel.java:85)
   > 	at com.carrotsearch.randomizedtesting.ClassModel.methodsModel(ClassModel.java:212)
   > 	at com.carrotsearch.randomizedtesting.ClassModel.<init>(ClassModel.java:207)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner.<init>(RandomizedRunner.java:319)
   > 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   > 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   > 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   > 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
   > 	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)
   > 	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)
   > 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
   > 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
   > 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
   > 	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
   > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:194)
   > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:310)
   > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
Completed in 0.09s, 1 test, 1 error <<< FAILURES!

Tests with failures:
  - org.elasticsearch.river.rss.integration.RssRiverAllParametersTest (suite)
  - org.elasticsearch.river.rss.unit.RomeTest.initializationError
  - org.elasticsearch.river.rss.unit.RssToJsonTest.initializationError

[INFO] JVM J0:     1.98 ..     5.06 =     3.08s
[INFO] Execution time total: 5.11 sec.
[INFO] Tests summary: 3 suites, 2 tests, 1 suite-level error, 2 errors
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.084 s
[INFO] Finished at: 2015-05-26T17:29:32-04:00
[INFO] Final Memory: 25M/62M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.0.12:junit4 (tests) on project rssriver: Execution tests of goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.0.12:junit4 failed: /opt/elasticsearch-1.5.2/riverSource/rssriver-master/target/junit4-ant-949337388347557628.xml:16: There were test failures: 3 suites, 2 tests, 1 suite-level error, 2 errors -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by dadoonet** [comment]
Project stopped.
